### ISSUE TITLE
Image embedding for Heraldicon and DrawShield

### ISSUE THREAD

**Issue by AragornFire** [mirnovov/heraldtron#16]
Heraldtron seems to currently be having issues with embedding images from Heraldicon and DrawShield. Lmk if this isn't the best place to report this.

**Comment by mirnovov** [comment]
Thanks, this is a good place to report an issue like this. I'll look into it.

**Comment by mirnovov** [comment]
@AragornFire Heraldicon seems to work for me - if I do `!hd azure` it shows up as expected. As for DrawShield it appears to be an issue on their end - I've lodged it in their issue tracker.

**Comment by mirnovov** [comment]
drawshield/Drawshield-Code#677 is resolved so closing this.
