### ISSUE TITLE
Add a !symbolism command to show an armiger's ROA symbolism

### ISSUE THREAD

**Issue by thomasylee** [mirnovov/heraldtron#7]
Hi there! From [this discussion on the Heraldry Discord server](https://discord.com/channels/272117928298676225/1115038638682677279), there has been interest in adding a `!symbolism` / `!s` command to show the symbolism for an armiger's COA on roll-of-arms.com.

I noticed that each armiger's GreiiN, Discord name, and blazon are retrieved from [a Word doc (book) in Google Drive](https://github.com/mirnovov/heraldtron/blob/743bf5ea0e693cb545ff95d6e333bf92573ac6f3/ht/cogs/tasks.py#L94C4-L98) and written to the `armigers` table.

It looks like the following changes would be needed to add the new command:
1. Update the `armigers` table schema to include a `symbolism` TEXT column.
1. Update whatever is updating the Word doc to also include the symbolism section for each armiger.
1. Update [write_book](https://github.com/mirnovov/heraldtron/blob/743bf5ea0e693cb545ff95d6e333bf92573ac6f3/ht/cogs/tasks.py#LL81C6-L81C16) to be able to distinguish blazon sections from symbology sections (i.e. regex fun).
1. Update [sync_book](https://github.com/mirnovov/heraldtron/blob/743bf5ea0e693cb545ff95d6e333bf92573ac6f3/ht/cogs/tasks.py#LL93C28-L93C28) to include the symbolism column when inserting records.
1. Adding the new command to [HeraldryRoll](https://github.com/mirnovov/heraldtron/blob/743bf5ea0e693cb545ff95d6e333bf92573ac6f3/ht/cogs/roll.py#L5).

I'm happy to submit a PR, but I'm not sure what is updating the Word doc in Google Drive and where its code lives.

Also, if you would like any assistance with deploying the changes, I'd be happy to help with that as well. If that's the case, the following info would be helpful:
1. How to update the database schema of the existing server's database.
1. How to deploy the code changes to the existing server (and whatever is updating the Word Doc).

Thanks for the help!

**Comment by mirnovov** [comment]
Why would the symbolism be a separate command? From my perspective it makes more sense to include that in the `!armiger` command. One less command to remember - but that's just my opinion ofc.

As for the document, it is manually updated by GreiiEquites. He appears to be still updating it, according to the bot the last change to it was two days ago. So you'd have to ask him about including a symbolism section in that.
  
Another possibility is just checking to see if the wiki pages have a symbolism section (which should be easy, as the MediaWiki API makes it easy to grab that text, and the page names are GreiiNs already). My plan for the bot when I was still active was actually to eventually make the `!a` command use the wiki when possible and only do use the Drive doc as a fallback. Though that'd be probably too much of a big thing to add now, but it should be easy to just excerpt the symbolism section from them.
 
> How to update the database schema of the existing server's database.

IIRC I just manually did that with SQL commands, there's no fancy migration or anything. Though I eventually wanted to add that.

> How to deploy the code changes to the existing server (and whatever is updating the Word Doc).

It's just pulled from this repository onto a VPS. Since I was pretty much the only committer, again that is just done manually once I had tested it enough on my local instance (which uses a separate Heraldtron Test Discord user).

**Comment by thomasylee** [comment]
Thanks for the info!

> Why would the symbolism be a separate command? From my perspective it makes more sense to include that in the !armiger command.

I suspect the suggestion may have been due to some of the symbolism sections being quite large ([example](https://roll-of-arms.com/wiki/GreiiN:169)), though maybe with pagination like on the bot's help menu, it might be manageable as part of `!a`. I agree it'd be easier having fewer commands to remember if we can.

> As for the document, it is manually updated by GreiiEquites.

I had a quick chat with Greii last night and he mentioned that it was intentional keeping the book focused on blazons and having the additional details on the website.

He said he could add symbolism to it too if there is demand for it, but I agree with you that pulling it from the website is probably just as straightforward, especially as I see the wiki conveniently has a `Symbolism` css id readily available for finding the section.

I think I have all I need to work on a PR now. We'll just need to run this on the db at some point before deploying the code to add the new column:
```
ALTER TABLE armigers ADD symbolism TEXT
```

**Comment by mirnovov** [comment]
Sounds great, thanks!

**Comment by thomasylee** [comment]
Which Discord intents need to be enabled to run the bot locally? I've set my `DISCORD_TOKEN` and `GCS_TOKEN` in config.json.

Here's the error I've been getting when trying to run the bot:
```
...
  File "/Users/tom/Programming/heraldtron/ht/__main__.py", line 182, in main
    await bot.start(bot.conf["DISCORD_TOKEN"])
  File "/Users/tom/Programming/heraldtron/.venv/lib/python3.11/site-packages/discord/client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "/Users/tom/Programming/heraldtron/.venv/lib/python3.11/site-packages/discord/client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
```

I created a [PR-9](https://github.com/mirnovov/heraldtron/pull/9) to show what I have so far. I tested the HTML-grabbing and parsing parts separately; I just haven't been able to test it as part of the bot yet.

Thanks again for your support! I tried responding to your DM in Discord but it looks like a permission restriction prevented me from being able to reply. All good though!

**Comment by mirnovov** [comment]
@thomasylee the intents that the bot requires are listed [here](https://github.com/mirnovov/heraldtron/blob/676a3a6c11208c44a6d37e409fc94e095ff8c3ae/ht/__main__.py#L47).

Notably, it requires the **Presence**, **Server Members** and **Message Content** privileged intents.
